apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: backend-onboarding-cron
spec:
  # Time is in GMT, it will run on every 5mins
  # https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/ScheduledEvents.html
  # https://crontab.cronhub.io/
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: backend-onboarding-cron
              image: CONTAINER_IMAGE
              envFrom:
                - configMapRef:
                    name: backend-onboarding
              imagePullPolicy: Always
              command:
                [
                  "sh",
                  "-c",
                  "ENVFILE=backend_onboarding_env node ./app/functions/100ms/DisableRoom/index.js",
                ]
          restartPolicy: OnFailure
